#!/usr/bin/env python3
"""Generate an ibsim netlist for a two-tier fat-tree.

    python3 ibfabric/gen_netlist.py --spines 4 --leaves 8 --hosts-per-leaf 16

Why this exists: the point of ibsim is scale the Ethernet lab cannot reach. Six
physical cores cap CML at a handful of booted nodes, but a 140-node IB fabric
here is a few hundred KB of userspace state. So the sizing knobs default to
something that looks like a real HPC pod rather than something that looks like
the CML topology.

Netlist format (from ibsim's net-examples), both ends of every link declared:

    Switch  <ports> "<nodeid>"
    [localport]     "<remoteid>"[remoteport]

The first port in the file is the SM port, so the first spine leads.

Hosts named in --real-hosts are placed first, so a live Linux box can attach to
this fabric as that HCA with SIM_HOST=<name> and claim its identity.
"""

from __future__ import annotations

import argparse
from pathlib import Path

OUT = Path(__file__).resolve().parent / "netlists"

# Mellanox-ish radix. Real fat-trees are built from fixed-radix switches, and
# keeping that constraint visible is half the point of modelling it.
SWITCH_PORTS = 36
HCA_PORTS = 2


def build(spines: int, leaves: int, per_leaf: int, real_hosts: list[str],
          sm_hosts: list[str] = ()) -> str:
    uplinks = spines  # every leaf lands one port on every spine
    if per_leaf + uplinks > SWITCH_PORTS:
        raise SystemExit(
            f"leaf needs {per_leaf} down + {uplinks} up = {per_leaf + uplinks} "
            f"ports, but the switch radix is {SWITCH_PORTS}")
    if leaves > SWITCH_PORTS:
        raise SystemExit(f"{leaves} leaves exceeds a {SWITCH_PORTS}-port spine")

    total = leaves * per_leaf
    if len(real_hosts) > total:
        # Silently dropping them means SIM_HOST=<dropped name> fails later with
        # nothing pointing back to here.
        raise SystemExit(
            f"{len(real_hosts)} real hosts named but the fabric only has {total} "
            f"HCAs: {', '.join(real_hosts[total:])} would not exist")
    names = list(real_hosts)
    names += [f"h{i:03d}" for i in range(len(names) + 1, total + 1)]

    # Subnet-manager hosts (the UFM pair) take the last slot of leaves spread
    # across the fabric -- first and last leaf for two -- so losing one leaf
    # cannot take out both SMs. Same reason real UFM HA pairs sit on different
    # leaves.
    for k, sm in enumerate(sm_hosts):
        leaf_idx = 0 if len(sm_hosts) == 1 else round(k * (leaves - 1) / (len(sm_hosts) - 1))
        names[leaf_idx * per_leaf + per_leaf - 1] = sm

    def host_of(leaf_idx: int, slot: int) -> str:
        return names[leaf_idx * per_leaf + slot]

    lines = [
        "# Two-tier fat-tree, generated by ibfabric/gen_netlist.py -- do not hand-edit.",
        f"# {spines} spines, {leaves} leaves, {per_leaf} HCAs per leaf = {total} hosts.",
        f"# Switch radix {SWITCH_PORTS}; leaf uses {per_leaf} down + {uplinks} up.",
        "",
    ]

    # Spines first: the very first port in the file is where the SM attaches.
    for s in range(1, spines + 1):
        lines.append(f'Switch\t{SWITCH_PORTS} "ibspine{s}"')
        for l in range(1, leaves + 1):
            lines.append(f'[{l}]\t"ibleaf{l}"[{per_leaf + s}]')
        lines.append("")

    for l in range(1, leaves + 1):
        lines.append(f'Switch\t{SWITCH_PORTS} "ibleaf{l}"')
        for slot in range(per_leaf):
            lines.append(f'[{slot + 1}]\t"{host_of(l - 1, slot)}"[1]')
        for s in range(1, spines + 1):
            lines.append(f'[{per_leaf + s}]\t"ibspine{s}"[{l}]')
        lines.append("")

    for l in range(1, leaves + 1):
        for slot in range(per_leaf):
            lines.append(f'Hca\t{HCA_PORTS} "{host_of(l - 1, slot)}"')
            lines.append(f'[1]\t"ibleaf{l}"[{slot + 1}]')
            lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spines", type=int, default=4)
    ap.add_argument("--leaves", type=int, default=8)
    ap.add_argument("--hosts-per-leaf", type=int, default=16)
    ap.add_argument("--real-hosts", default="jump,srv-app1,srv-db1",
                    help="comma-separated names placed first, so live Linux "
                         "hosts can attach as those HCAs via SIM_HOST")
    ap.add_argument("--sm-hosts", default="ufm1,ufm2",
                    help="comma-separated subnet-manager hosts, spread across "
                         "leaves; start_fabric.sh runs one OpenSM on each")
    ap.add_argument("--out", default="fat-tree.net")
    args = ap.parse_args()

    real = [h.strip() for h in args.real_hosts.split(",") if h.strip()]
    sms = [h.strip() for h in args.sm_hosts.split(",") if h.strip()]
    text = build(args.spines, args.leaves, args.hosts_per_leaf, real, sms)

    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / args.out
    path.write_text(text)
    hosts = args.leaves * args.hosts_per_leaf
    print(f"wrote {path}")
    print(f"  {args.spines} spines + {args.leaves} leaves + {hosts} HCAs "
          f"= {args.spines + args.leaves + hosts} nodes")
    print(f"  attachable as real hosts: {', '.join(real)}")
    print(f"  subnet-manager hosts: {', '.join(sms)}")


if __name__ == "__main__":
    main()
